### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by Noskcaj10** [mikeage/prpltwtr#10]
Please release the current git as a new version, since many users aren't keen to install from git. This would also allow ubuntu and debian to use prpltwtr

**Comment by mikeage** [comment]
I will tag a version before January so that Ubuntu and Debian can include a package. For other Linux users, you'll need to compile anyway, so I don't know if there's value in an official release.

For Windows, it's important, but I'm investigating one crash before I want to release a Windows version.
